baseURL = 'https://blog.dtan13.me'
languageCode = 'en-us'
title = 'Blog - DTan13'
theme = 'uBlogger'
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true

[[menu.main]]
identifier = 'posts'
pre = ''
post = ''
name = 'Posts'
url = '/posts/'
title = 'Posts'
weight = 1

[[menu.main]]
identifier = 'tags'
pre = ''
post = ''
name = 'Tags'
url = '/tags/'
title = 'Tags'
weight = 2

[[menu.main]]
identifier = 'categories'
pre = ''
post = ''
name = 'Categories'
url = '/categories/'
title = 'Categories'
weight = 3

[[menu.main]]
identifier = 'about'
pre = ''
post = ''
name = 'About'
url = 'https://dtan13.tech'
title = 'About'
weight = 4

[params]
version = '2.0.X'
description = 'Just a Blog'
keywords = ['DTan13', 'Dhananjay', 'Tanpure', 'Dhananjay Tanpure']
defaultTheme = 'dark'
gitRepo = 'https://github.com/DTan13/blog.dtan13.tech'
dateFormat = '02-Jan-2006'

[params.app]
title = 'DTan13'
noFavicon = false
themeColor = '#ffffff'
iconColor = '#5bbad5'
tileColor = '#da532c'

[params.header]
desktopMode = 'fixed'
mobileMode = 'auto'

[params.header.title]
name = 'DTan13'
pre = ''
post = ''

[params.footer]
enable = true
custom = ''
hugo = false
copyright = true
author = false
since = 2021
icp = ''
# workaround for author(sorry!)
license = 'Dhananjay Tanpure'

[params.section]
paginate = 20
dateFormat = '01-02'
rss = 10

[params.list]
paginate = 20
dateFormat = '01-02'
rss = 10

[params.home]
rss = 10

[params.home.profile]
enable = true
title = 'Dhananjay Tanpure'
avatarURL = '/images/avatar.png'
subtitle = 'Exploring!'
social = true

[params.home.posts]
enable = true
paginate = 5

[params.social]
GitHub = 'dtan13'
Linkedin = 'dtan13'
Twitter = '_DTan13_'
Instagram = 'dtan.13'
Facebook = ''
Telegram = 'DTan13'
Medium = ''
Gitlab = 'DTan13'
Youtubelegacy = ''
Youtubecustom = ''
Youtubechannel = ''
Tumblr = ''
Quora = ''
Keybase = 'dtan13'
Pinterest = ''
Reddit = 'DTan13'
Codepen = ''
FreeCodeCamp = ''
Bitbucket = ''
Stackoverflow = '10990171'
Weibo = ''
Odnoklassniki = ''
VK = ''
Flickr = ''
Xing = ''
Snapchat = ''
Soundcloud = ''
Spotify = ''
Bandcamp = ''
Paypal = ''
Fivehundredpx = ''
Mix = ''
Goodreads = ''
Lastfm = ''
Foursquare = ''
Hackernews = ''
Kickstarter = ''
Patreon = 'dtan13'
Steam = ''
Twitch = ''
Strava = ''
Skype = ''
Whatsapp = ''
Zhihu = ''
Douban = ''
Angellist = ''
Slidershare = ''
Jsfiddle = ''
Deviantart = ''
Behance = ''
Dribbble = ''
Wordpress = ''
Vine = ''
Googlescholar = ''
Researchgate = 'Dhananjay-Tanpure'
Mastodon = ''
Thingiverse = ''
Devto = 'dtan13'
XMPP = ''
Matrix = ''
Bilibili = ''
Discord = ""
Email = 'dtan13@pm.me'
RSS = true

[params.page]
hiddenFromHomePage = false
hiddenFromSearch = false
twemoji = false
lightgallery = false
ruby = true
fraction = true
fontawesome = true
linkToMarkdown = false
rssFullText = false

[params.page.toc]
enable = true
keepStatic = false
auto = false

[params.page.math]
enable = true
blockLeftDelimiter = ''
blockRightDelimiter = ''
inlineLeftDelimiter = ''
inlineRightDelimiter = ''
copyTex = true
mhchem = true

[params.page.code]
copy = true
maxShownLines = 50

[params.page.share]
enable = true
Twitter = true
Facebook = true
Linkedin = true
Whatsapp = true
Pinterest = true
Tumblr = true
HackerNews = true
Reddit = true
VK = false
Buffer = false
Xing = false
Line = false
Instapaper = false
Pocket = true
Digg = false
Stumbleupon = false
Flipboard = true
Weibo = false
Renren = false
Myspace = false
Blogger = true
Baidu = false
Odnoklassniki = false
Evernote = false
Skype = true
Trello = true
Mix = false

[params.comment]
enable = true

[params.comment.gitalk]
enable = true
owner = 'DTan13'
repo = 'blog.dtan13.tech.comments'
clientId = '50369ddf8e4c9ad319b1'
clientSecret = 'd7c91e37cd6074c34adb794e0281d1888645e9d8'

[params.compatibility]
polyfill = false
objectFit = false

[markup]

[markup.goldmark]

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingID = true
autoHeadingIDType = 'github'

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
anchorLineNos = false
codeFences = false
guessSyntax = true
lineNos = false
lineNumbersInTable = false
noClasses = false
tabWidth = 4

[markup.tableOfContents]
startLevel = 2
endLevel = 6

[sitemap]
changefreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[Permalinks]
posts = ':year/:month/:day/:filename'

[privacy.googleAnalytics]

[privacy.twitter]
enableDNT = true

[privacy.youtube]
privacyEnhanced = true

[mediaTypes."text/plain"]
suffixes = ['md']

[outputFormats.MarkDown]
mediaType = 'text/plain'
isPlainText = true
isHTML = false

[outputs]
home = ['HTML', 'RSS', 'JSON']
page = ['HTML', 'MarkDown']
section = ['HTML', 'RSS']
taxonomy = ['HTML', 'RSS']
taxonomyTerm = ['HTML']
